In [1]:
%load_ext autoreload
%autoreload 2
import manenv
from manenv.utils.product_utils import *
from manenv.core.world import World
from manenv.core.component import *
from manenv.render_wrapper import RenderWrapper
from manenv.core.product import *
from manenv.core.effector import *

import manenv.effectors as eff
import manenv.components as cmp


pygame-ce 2.4.1 (SDL 2.28.5, Python 3.11.9)


In [2]:
world = World((3, 3))
s = np.zeros((5, 5), dtype=np.int8)
s[1][2] = 2
s[1][1] = 2
s[2][1] = 1
s[3][1] = 1
product = Product(s)
world.place_component(make_vector(1, 1), cmp.Conveyor(
    np.array([
    [0, 0, 0],
    [1, 0, -1],
    [0, 0, 0]
])))
world.place_component(make_vector(2, 0), cmp.Conveyor(
    np.array([
    [0, -1, 0],
    [0, 0, 1],
    [0, 0, 0] 
])))
world.place_component(make_vector(2, 1), cmp.Outport())

grabber = eff.Grabber(make_vector(0, 2))
buddy = eff.Grabber(make_vector(1, 3))
welder = eff.Welder(make_vector(1, 2))
transformer = eff.Transformer(1, 2, make_vector(2,  4))
discard = eff.Acceptor(make_vector(1, 7))

world.place_component(make_vector(1, 2), cmp.Spawner(product))
assembler : cmp.Assembler = cmp.Assembler(make_vector(10, 10), [grabber, buddy, welder, discard])
world.place_component(make_vector(1, 0), assembler)
wrapper = RenderWrapper(world)

In [3]:
# wrapper.reset()
# assembler.place_in_inventory(product.copy())
# assembler.place_in_inventory(product.copy())
# world.update()

# grabber.set_action(eff.GrabberActions.GRAB_INVENTORY.value)
# grabber.set_action(eff.GrabberActions.GRAB_INVENTORY.value)
# buddy.set_action(eff.GrabberActions.GRAB_INVENTORY.value)
# world.update()

# grabber.set_action(eff.GrabberActions.RELEASE.value)
# buddy.set_action(eff.GrabberActions.RELEASE.value)
# world.update()

# welder.set_action(eff.WelderActions.WELD_EAST.value)
# world.update()
# world.update()

# grabber.set_action(eff.GrabberActions.GRAB.value)
# world.update()

# grabber.set_action(eff.GrabberActions.MOVE_RIGHT.value)
# world.update()

# grabber.set_action(eff.GrabberActions.RELEASE.value)
# world.update()

# transformer.set_action(eff.TransformerActions.TRANSFORM.value)
# world.update()
# world.update()

# grabber.set_action(eff.GrabberActions.MOVE_RIGHT.value)
# world.update()
# world.update()

# grabber.set_action(eff.GrabberActions.MOVE_RIGHT)
# world.update()

# grabber.set_action(eff.GrabberActions.MOVE_RIGHT)
# world.update()


In [4]:
# wrapper.render()

# Gym Environment Test

In [5]:
from manenv.gym_wrapper import MARLFactoryEnvironment

In [6]:
world.reset()
environment = MARLFactoryEnvironment(world)
renderer = RenderWrapper(environment._world)

In [7]:
from pettingzoo.test import parallel_api_test

In [9]:
parallel_api_test(environment, num_cycles=1_000_000)

[0 5] [0 5] id: 805
[[2 2]
 [1 0]
 [1 0]] id: 805
[[2 2]
 [1 0]
 [1 0]]
[0 5] [0 5] id: 1260
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1260
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[0 5] [0 5] id: 1277
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1277
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[0 5] [0 5] id: 1280
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1280
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[0 5] [1 4] id: 1286
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 816
[[1 1 2]
 [0 0 2]]
[0 5] [0 5] id: 817
[[2 2]
 [1 0]
 [1 0]] id: 817
[[2 2]
 [1 0]
 [1 0]]
[0 5] [0 5] id: 1330
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1330
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[0 5] [0 5] id: 1332
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1332
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[0 5] [0 5] id: 1336
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1336
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[0 5] [0 5] id: 1349
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1349
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[2 5] [2 5] id: 1357
[[2. 2.]
 [1. 0.]
 [1. 0.]] id: 1357
[[2. 2.]
 [1. 0.]
 [1. 0.]]
[ 1 -1] [ 1 -1] id: 789
[[1 1 2]
 [0 0 2]] id: 789
[[1 1 2]
 [0 0 2]]


ValueError: could not broadcast input array from shape (2,3) into shape (2,0)

In [ ]:
for _ in range(100):
    action = environment._action_space.sample()
    environment.step(action)
renderer.render()

KeyError: 12