In [1]:
%load_ext autoreload
%autoreload 2
import manenv
from manenv.product_utils import *
from manenv.world import World
from manenv.component import *
from manenv.render_wrapper import RenderWrapper
from manenv.product import *
from manenv.effector import *

pygame-ce 2.4.1 (SDL 2.28.5, Python 3.12.2)


In [2]:
world = World((3, 3))
s = np.zeros((5, 5), dtype=np.int8)
s[1][2] = 2
s[1][1] = 2
s[2][1] = 1
product = Product(s)
world.place_component(make_vector(1, 2), Spawner(product))
world.place_component(make_vector(1, 1), Conveyor(
    np.array([
    [1, 0, 0],
    [1, 0, -1],
    [1, 0, 0]
])))

grabber = Grabber()
assembler = Assembler(make_vector(10, 10), [grabber])
world.place_component(make_vector(1, 0), assembler)
wrapper = RenderWrapper(world)

In [3]:
assembler.place_in_inventory(product.copy())
grabber.execute_action(GrabberActions.GRAB_INVENTORY)
grabber.execute_action(GrabberActions.RELEASE)
grabber.execute_action(GrabberActions.GRAB)
grabber.execute_action(GrabberActions.MOVE_RIGHT)
grabber.execute_action(GrabberActions.MOVE_RIGHT)
grabber.execute_action(GrabberActions.MOVE_RIGHT)
grabber.execute_action(GrabberActions.ROTATE_CCW)
grabber.execute_action(GrabberActions.RELEASE)

[[2 2]
 [1 0]]
[[2 0]
 [2 1]]


In [4]:
wrapper.render(update_mode=True)

[[0 0 0 2 0 0 0 0 0 0]
 [0 0 0 2 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
