## A simple swarm

In [21]:
%load_ext autoreload 
%autoreload 2
import sys
sys.tracebacklimit = 0

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [22]:
from core.agent import *
from core.world import * 
from core.map import *
import numpy as np
from core.render import * 

In [23]:
world = World(dims = (100, 100),
              resource_generator= RandomMapGenerator(),
              energy_model=EnergyModel()
              )
swarm = [Agent() for i in range(1000)]
for agent in swarm:
    world.add_agent(agent)

In [24]:
swarm = initialize_positions_randomly(world, swarm)

In [25]:
# Test movements by doing random actions
def update():
    for agent in swarm:
        action_choice = np.random.randint(0, 3)
        choice = np.random.randint(1, 5)

        match (action_choice): 
            case 1: agent.move(choice)
            case 2: agent.pick_up(choice)
            case 3: agent.put_down(choice)

    world.update()

update()

ValueError: a must be greater than 0 unless no samples are taken

In [17]:
render_world(world, (800, 800), update_fn=update, delay_s=0)

## Verify certain things about the simulation

In [20]:
# Validate the observation space provided is sensible
obs = swarm[0].get_observation()

print(obs.nearby_agents, obs.nearby_agents.shape)

[[  0   0  58   0   0   0   0]
 [  0   0 655 900   0   0 877]
 [  0   0   0 231 770  64 131]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0 410 278   0   0   0   0]
 [  0 982 352   0   0   0   0]] (7, 7)


In [19]:
# Validate that all swarm agents landed in different positions
positions = set()
for agent in swarm:
    pos = agent.get_current_position()
    positions.add((pos[0], pos[1]))

print(len(positions), len(world.get_agents()))

1000 1000
