## A simple swarm

In [1]:
%load_ext autoreload 
%autoreload 2
import sys
sys.tracebacklimit = 0

In [2]:
from core.agent import *
from core.world import * 
from core.map import *
import numpy as np
from core.render import * 

pygame-ce 2.4.1 (SDL 2.28.5, Python 3.11.9)


In [3]:
world = World(dims = (100, 100),
              resource_generator= RandomMapGenerator(),
              energy_model=EnergyModel()
              )
swarm = [Agent() for i in range(1000)]
for agent in swarm:
    world.add_agent(agent)

In [4]:
swarm = initialize_positions_randomly(world, swarm)

In [5]:
# Test movements by doing random actions
def update():
    for agent in swarm:
        action_choice = np.random.randint(0, 3)
        choice = np.random.randint(1, 5)

        match (action_choice): 
            case 1: agent.move(choice)
            case 2: agent.pick_up(choice)
            case 3: agent.put_down(choice)

    world.update()

update()

In [6]:
render_world(world, (800, 800), update_fn=update, delay_s=0)

## Verify certain things about the simulation

In [7]:
# Validate the observation space provided is sensible
obs = swarm[0].get_observation()

print(obs.nearby_agents, obs.nearby_agents.shape)

[[  0 643   0   0   0   0 928]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0 626   0]
 [  0   0 962   0   0   0   0]
 [  0   0   0  97   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]] (7, 7)


In [8]:
# Validate that all swarm agents landed in different positions
positions = set()
for agent in swarm:
    pos = agent.get_current_position()
    positions.add((pos[0], pos[1]))

print(len(positions), len(world.get_agents()))

1000 1000


In [14]:
# Check for resources
rsrc_qty = world._resource_grid._resource_quantity_map
qtys = []

for i in range(rsrc_qty.shape[0]):
    for j in range(rsrc_qty.shape[1]):
        if rsrc_qty[i, j] > 0:
            qtys.append(rsrc_qty[i, j])

print(qtys)

[0.6110919955633651, 2.370733806385301, 0.16728746128593386, 1.5098635159460398, 2.7243798350637753, 5.574852035172111, 5.602647698771065, 4.151024258825512, 5.998274651195041, 6.539925888788501, 3.0115275884404573, 1.9119179020439594, 4.205504355636432, 3.394384436815744, 2.8916609705644, 3.7697746424113268, 4.0253062177259284, 1.5245421322658208, 1.5820439121915726, 3.377206341597434, 5.7351820668024125, 4.962901674188159, 4.106315406614795, 6.410379906970591, 6.368410221521635, 5.265501058928705, 6.94078650829784, 1.2814370996021207, 8.03906310245369, 5.362219951982684, 6.1329906100638265, 8.508571135693947, 3.124469080480271, 6.620990140559929, 4.831569400305191, 5.300893069511563, 0.4929321294367095, 1.4447977033230197, 1.747342488489501, 2.281032639864618, 3.3511095335850074, 6.284193875860417, 7.163394487490782, 6.030724274208845, 4.3381040674662055, 6.819705033146576, 1.7614246948871766, 3.6543822806911703, 6.314631770645088, 0.05189470048154199, 6.181861705202269, 3.2000914308

In [ ]:
# Check for agent state
state = swarm[0]._current_state.inventory
print(state)
