## A simple swarm

In [8]:
%load_ext autoreload 
%autoreload 2
import sys
sys.tracebacklimit = 0

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
from core.agent import *
from core.world import * 
import numpy as np
from core.render import * 

In [10]:
world = World(dims = (100, 100),
              resource_generator= ResourceGenerator())
swarm = [Agent() for i in range(1000)]
for agent in swarm:
    world.add_agent(agent)

TypeError: World.__init__() missing 1 required positional argument: 'resource_generator'

In [4]:
swarm = initialize_positions_randomly(world, swarm)

In [5]:
# Test movements by doing random actions
def update():
    for agent in swarm:
        choice = np.random.randint(1, 5)
        agent.move(choice)

    world.update()

update()

In [6]:
render_world(world, (800, 800), update_fn=update, delay_s=0)

## Verify certain things about the simulation

In [7]:
# Validate the observation space provided is sensible
obs = swarm[0].get_observation()

print(obs.nearby_agents, obs.nearby_agents.shape)

[[  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   6]
 [  0 369   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0 765   0   0 443]] (7, 7)
