## A simple swarm

In [68]:
%load_ext autoreload 
%autoreload 2
import sys
sys.tracebacklimit = 0

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [69]:
from core.agent import *
from core.world import * 
from core.map import *
import numpy as np
from core.render import * 

In [70]:
world = World(dims = (100, 100),
              resource_generator= RandomMapGenerator(),
              energy_model=EnergyModel()
              )
swarm = [Agent() for i in range(1000)]
for agent in swarm:
    world.add_agent(agent)

In [71]:
swarm = initialize_positions_randomly(world, swarm)

In [72]:
# Test movements by doing random actions
def update():
    for agent in swarm:
        action_choice = np.random.randint(0, 3)
        choice = np.random.randint(1, 5)

        match (action_choice): 
            case 1: agent.move(choice)
            case 2: agent.pick_up(choice)
            case 3: agent.put_down(choice)

    world.update()

update()

In [73]:
render_world(world, (800, 800), update_fn=update, delay_s=0)

## Verify certain things about the simulation

In [74]:
# Validate the observation space provided is sensible
obs = swarm[0].local_observation

print(obs.nearby_agents, obs.nearby_agents.shape)
print(obs.resource_types, obs.resource_types.shape)

[[  0   0 547   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0 711   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0 694   0 693   0]
 [  0   0   0   0   0   0   0]] (7, 7)
[[4 4 0 0 0 0 0]
 [4 4 0 0 0 0 0]
 [4 4 0 0 0 0 0]
 [4 4 0 0 0 0 0]
 [4 4 0 0 0 0 0]
 [4 4 0 0 0 0 0]
 [0 0 1 1 1 1 1]] (7, 7)


In [75]:
# Validate that all swarm agents landed in different positions
positions = set()
for agent in swarm:
    pos = agent.current_position
    positions.add((pos[0], pos[1]))

print(len(positions), len(world.get_agents()))

1000 1000


In [76]:
# Check for resources
rsrc_qty = world._resource_map._resource_quantity_map
qtys = []

for i in range(rsrc_qty.shape[0]):
    for j in range(rsrc_qty.shape[1]):
        if rsrc_qty[i, j] > 0:
            qtys.append(rsrc_qty[i, j])

print(qtys)

[4.964490337638731, 5.07036034433135, 4.4909753403220085, 4.765117993484319, 8.53584253905084, 8.38736018599896, 6.678359429430234, 5.886812366659498, 2.068993223446637, 5.989869939327151, 4.621843128013672, 3.814511122183374, 5.997667383377536, 1.7407874590654226, 2.4515485405995663, 5.01862541574001, 7.199698671667337, 2.0676687325219456, 2.001804667999592, 6.72872445523268, 4.457762196461819, 4.606562822423272, 7.7353331714916855, 3.2676756906842606, 2.7185639681474303, 4.908501316556711, 7.315123484722583, 5.865993072428396, 8.209002341410045, 3.191074784967266, 4.500782901139996, 5.419093055924112, 5.031324177955058, 4.771504121383582, 3.9600687126378036, 8.750614860789707, 2.0250792721608954, 5.928832852291245, 1.6606616517844155, 7.085397877466399, 5.204159352289743, 4.510129542341292, 7.126637380633024, 2.9690693001515363, 3.867580970678741, 4.544708134557708, 4.780936701217491, 4.49038410871146, 5.634114159457868, 6.16049291509192, 3.8663627340901305, 3.984878401968591, 7.4934

In [77]:
# Check for agent state
state = swarm[0]._current_state.inventory
print(state)


[Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0)]
