## A simple swarm

In [51]:
%load_ext autoreload 
%autoreload 2
import sys
sys.tracebacklimit = 0

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [52]:
from core.agent import *
from core.world import * 
from core.map import *
import numpy as np
from core.render import * 

In [53]:
world = World(dims = (100, 100),
              resource_generator= RandomMapGenerator(),
              energy_model=EnergyModel()
              )
swarm = [Agent() for i in range(1000)]
for agent in swarm:
    world.add_agent(agent)

In [54]:
swarm = initialize_positions_randomly(world, swarm)

In [55]:
# Test movements by doing random actions
def update():
    for agent in swarm:
        action_choice = np.random.randint(0, 3)
        choice = np.random.randint(1, 5)

        match (action_choice): 
            case 1: agent.move(choice)
            case 2: agent.pick_up(choice)
            case 3: agent.put_down(choice)

    world.update()

update()

In [56]:
render_world(world, (800, 800), update_fn=update, delay_s=0)

## Verify certain things about the simulation

In [57]:
# Validate the observation space provided is sensible
obs = swarm[0].get_observation()

print(obs.nearby_agents, obs.nearby_agents.shape)
print(obs.resource_types, obs.resource_types.shape)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] (7, 7)
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] (7, 7)


In [50]:
# Validate that all swarm agents landed in different positions
positions = set()
for agent in swarm:
    pos = agent.get_current_position()
    positions.add((pos[0], pos[1]))

print(len(positions), len(world.get_agents()))

1 1


In [25]:
# Check for resources
rsrc_qty = world._resource_map._resource_quantity_map
qtys = []

for i in range(rsrc_qty.shape[0]):
    for j in range(rsrc_qty.shape[1]):
        if rsrc_qty[i, j] > 0:
            qtys.append(rsrc_qty[i, j])

print(qtys)

[3.613147161963579, 4.109014209070697, 5.817721561069794, 3.460374778326755, 4.886986743499585, 5.91253829344065, 6.9771120091585175, 4.870457352018556, 3.3898622945706456, 3.5434065379356516, 0.27899328864395656, 3.1293314931775633, 4.370627181276903, 7.307644953381686, 7.768164398021092, 3.8704097648434885, 1.769446402607687, 3.47685948830384, 3.051150021573836, 1.6288012052859062, 9.119523628163474, 5.327793756666485, 4.335854105858226, 2.256698093286864, 4.854220583359963, 3.2436384606985444, 8.484458974689026, 0.6265206816208342, 3.9414309728809878, 3.586212407379139, 5.46868499617374, 5.967246982082206, 4.770380991290156, 10.399208469786839, 4.501581264203409, 5.167897737383475, 7.178001945764013, 3.3017490938894976, 5.020404906214236, 2.27633914446878, 6.9697979782901776, 2.026093733755514, 5.77125681879311, 7.2738147310832275, 2.6959880102383917, 5.369605780368396, 6.07128921595783, 7.726720578981977, 1.8995570309843157, 3.9448369192628445, 6.217094656029425, 4.928994182241093,

In [26]:
# Check for agent state
state = swarm[0]._current_state.inventory
print(state)


[Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0), Resource(type=4, quantity=1.0)]
