## A simple swarm

In [15]:
%load_ext autoreload 
%autoreload 2
import sys
sys.tracebacklimit = 0

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
from core.agent import *
from core.world import * 
from core.resource import *
import numpy as np
from core.render import * 

In [17]:
world = World(dims = (100, 100),
              resource_generator= RandomMapGenerator())
swarm = [Agent() for i in range(1000)]
for agent in swarm:
    world.add_agent(agent)

In [18]:
swarm = initialize_positions_randomly(world, swarm)

ValueError: a must be 1-dimensional

In [12]:
# Test movements by doing random actions
def update():
    for agent in swarm:
        choice = np.random.randint(1, 5)
        agent.move(choice)

    world.update()

update()

In [13]:
render_world(world, (800, 800), update_fn=update, delay_s=0)

## Verify certain things about the simulation

In [14]:
# Validate the observation space provided is sensible
obs = swarm[0].get_observation()

print(obs.nearby_agents, obs.nearby_agents.shape)

[[  0 164   0 427 233 686   0]
 [  0 373 172 627 433 906 693]
 [  0   0   0   0 269  60 528]
 [  0   0   0   0   0 278 732]
 [946   0   0   0   0   0 378]
 [  0   0   0   0   0 119 575]
 [  0 777 571   0   0   0   0]] (7, 7)
