In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from use_case.baseline import * 
from tests.eval import *

payoff_i = np.random.uniform(0, 10, (20, 20))
payoff_j = np.transpose(payoff_i).copy()

# Initialize environment
N_ACTIONS = payoff_i.shape[0]
N_AGENTS = 1000
env = BaselineEnvironment(N_AGENTS, payoff_i, payoff_j, total_games = 1)

# Actual Run

In [3]:
from models.model import *
from models.trainer import *


In [4]:
# Configure the network here
parameters = ParameterSettings(
    n_agents = N_AGENTS,
    d_action = N_ACTIONS, 
    d_obs = env.obs_size, 
    d_traits = 1,
    d_beliefs = 1
)
parameters.device = "cuda" if torch.cuda.is_available() else "cpu"

model = Model(parameters)

In [5]:
equilibriua = find_pure_equilibria(payoff_i, payoff_j)

for eq in equilibriua:
    x, y = eq 
    a = (y[0] + y[1]) / 2

    print(x, a)

(2, 2) 9.980245078428464
(6, 6) 8.913847217185843


In [6]:
evaluate_policy(model, env, 10)

Average Return: 4.9044310228749755
Total returns: 49.04431022874975
Action Distribution
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 43   8  85  12  29 103  30  72  12  31 163   6  63  61  17 108  23  32
   5  97]


In [ ]:
# Setup the training loop
training_parameters = TrainingParameters(
    actor_training_loops = 30,
    hypernet_training_loops= 15, 
    outer_loops = 200,
    actor_learning_rate= 0.01,
    experience_buffer_size = 3,
)

train_model(model, env, training_parameters)
        

Epoch 0


Hypernet Loop: 100%|██████████| 5/5 [00:02<00:00,  2.08it/s]


Average Return: 4.8245810805456415
Total returns: 48.245810805456415
Action Distribution
[ 1  3  5 10 12 13 14 15 17]
[ 26  38 371   1 130   5  24 267 138]


Actor Training: 100%|██████████| 10/10 [00:01<00:00,  6.41it/s]


Average Return: 5.134817210321354
Total returns: 51.34817210321354
Action Distribution
[ 1  2  3  5 11 12 13 14 15 17 18]
[ 72   6  30 274   1 130   3  39 320 118   7]
Epoch 1


Hypernet Loop: 100%|██████████| 5/5 [00:02<00:00,  2.27it/s]


Average Return: 6.4378038907740605
Total returns: 64.3780389077406
Action Distribution
[ 1  2  3  5 10 11 12 14 15 17]
[ 19 335   2 104   1   1 228 146 127  37]


Actor Training:   0%|          | 0/10 [00:00<?, ?it/s]


KeyboardInterrupt: 