In [23]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
from use_case.baseline import * 
from tests.eval import *

payoff_i = np.random.uniform(-10, 10, (10, 10))
payoff_j = np.transpose(payoff_i).copy()

# Initialize environment
N_ACTIONS = payoff_i.shape[0]
N_AGENTS = 1000
env = BaselineEnvironment(N_AGENTS, payoff_i, payoff_j, total_games = 1)

# Actual Run

In [25]:
from models.model import *
from models.trainer import *


In [26]:
# Configure the network here
parameters = ParameterSettings(
    n_agents = N_AGENTS,
    d_action = N_ACTIONS, 
    d_obs = env.obs_size, 
    d_traits = 1,
    d_beliefs = 1
)
parameters.device = "cuda" if torch.cuda.is_available() else "cpu"

model = Model(parameters)

In [27]:
equilibriua = find_pure_equilibria(payoff_i, payoff_j)

for eq in equilibriua:
    x, y = eq 
    a = (y[0] + y[1]) / 2

    print(x, a)

In [28]:
evaluate_policy(model, env, 10)

Average Return: 0.21203201293303872
Total returns: 2.1203201293303873
Action Distribution
[0 1 2 3 4 5 6 7 8 9]
[ 34 100 151 156  94 236  56  34  86  53]


In [ ]:
# Setup the training loop
training_parameters = TrainingParameters(
    actor_training_loops = 1, 
    outer_loops = 10,
    learning_rate= 0.01,
    experience_buffer_size = 3,
)

train_model(model, env, training_parameters)
        

Epoch 0


Actor Training: 100%|██████████| 100/100 [00:14<00:00,  6.72it/s]


Average Return: 1.2790560793027095
Total returns: 12.790560793027094
Action Distribution
[0 1 2 3 4 5 6 7 8 9]
[ 45 123 204  71  95 181 176  22   8  75]


Hypernet Loop:   0%|          | 0/5 [00:00<?, ?it/s]


RuntimeError: mat1 and mat2 shapes cannot be multiplied (6000x1 and 2x128)